Train:
  custom_data_split: false
  data_date: 2022-03-09
  data_type: full_aug
  do_pca: false
  full_data: true
  load_data: false
  test_size: 0.1
  
data:
  file: Data/full_data_03_08_aug.xlsx
  aug: true