Custom_Train:
  data_split_type: polymer
  hold_out: polymethylmethacrylate
  leave_out: Mw
Train:
  data_date: 2022-03-09
  data_type: polysplitnew_0_polymethylmethacrylate_t3
  do_pca: false
  full_data: false
  load_data: false
  model_date: 2022-11-22
  test_size: 0.1
data:
  aug: true
  file: ../Data/full_data_03_08_aug_MOD.xlsx
